module.exports = {
    database:{
        dbName:'siji',
        host:'localhost',
        port:3306,
        user:'root',
        password:'center135'
    },
    security:{
        secretKey:'yqm666',
        expiresIn:60*60*30*24
    },
    log:{
        debug:true,
        log:{
            path:'../log/',
            type:'console',
            level:'debug',
            mask:true
        }
    },
    image:{
        IMAGE_BASE_PATH:'\\public\\upload\\'
    }
}